# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/aurelien/workspace/cpp/projet-rob4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/aurelien/workspace/cpp/projet-rob4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aurelien/workspace/cpp/projet-rob4/CMakeFiles /home/aurelien/workspace/cpp/projet-rob4/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/aurelien/workspace/cpp/projet-rob4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Roomball

# Build rule for target.
Roomball: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Roomball
.PHONY : Roomball

# fast build rule for target.
Roomball/fast:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/build
.PHONY : Roomball/fast

src/Ball.o: src/Ball.cpp.o

.PHONY : src/Ball.o

# target to build an object file
src/Ball.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Ball.cpp.o
.PHONY : src/Ball.cpp.o

src/Ball.i: src/Ball.cpp.i

.PHONY : src/Ball.i

# target to preprocess a source file
src/Ball.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Ball.cpp.i
.PHONY : src/Ball.cpp.i

src/Ball.s: src/Ball.cpp.s

.PHONY : src/Ball.s

# target to generate assembly for a file
src/Ball.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Ball.cpp.s
.PHONY : src/Ball.cpp.s

src/Bonus.o: src/Bonus.cpp.o

.PHONY : src/Bonus.o

# target to build an object file
src/Bonus.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Bonus.cpp.o
.PHONY : src/Bonus.cpp.o

src/Bonus.i: src/Bonus.cpp.i

.PHONY : src/Bonus.i

# target to preprocess a source file
src/Bonus.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Bonus.cpp.i
.PHONY : src/Bonus.cpp.i

src/Bonus.s: src/Bonus.cpp.s

.PHONY : src/Bonus.s

# target to generate assembly for a file
src/Bonus.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Bonus.cpp.s
.PHONY : src/Bonus.cpp.s

src/BonusSize.o: src/BonusSize.cpp.o

.PHONY : src/BonusSize.o

# target to build an object file
src/BonusSize.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/BonusSize.cpp.o
.PHONY : src/BonusSize.cpp.o

src/BonusSize.i: src/BonusSize.cpp.i

.PHONY : src/BonusSize.i

# target to preprocess a source file
src/BonusSize.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/BonusSize.cpp.i
.PHONY : src/BonusSize.cpp.i

src/BonusSize.s: src/BonusSize.cpp.s

.PHONY : src/BonusSize.s

# target to generate assembly for a file
src/BonusSize.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/BonusSize.cpp.s
.PHONY : src/BonusSize.cpp.s

src/Element.o: src/Element.cpp.o

.PHONY : src/Element.o

# target to build an object file
src/Element.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Element.cpp.o
.PHONY : src/Element.cpp.o

src/Element.i: src/Element.cpp.i

.PHONY : src/Element.i

# target to preprocess a source file
src/Element.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Element.cpp.i
.PHONY : src/Element.cpp.i

src/Element.s: src/Element.cpp.s

.PHONY : src/Element.s

# target to generate assembly for a file
src/Element.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Element.cpp.s
.PHONY : src/Element.cpp.s

src/Field.o: src/Field.cpp.o

.PHONY : src/Field.o

# target to build an object file
src/Field.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Field.cpp.o
.PHONY : src/Field.cpp.o

src/Field.i: src/Field.cpp.i

.PHONY : src/Field.i

# target to preprocess a source file
src/Field.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Field.cpp.i
.PHONY : src/Field.cpp.i

src/Field.s: src/Field.cpp.s

.PHONY : src/Field.s

# target to generate assembly for a file
src/Field.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Field.cpp.s
.PHONY : src/Field.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Goal.o: src/Goal.cpp.o

.PHONY : src/Goal.o

# target to build an object file
src/Goal.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Goal.cpp.o
.PHONY : src/Goal.cpp.o

src/Goal.i: src/Goal.cpp.i

.PHONY : src/Goal.i

# target to preprocess a source file
src/Goal.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Goal.cpp.i
.PHONY : src/Goal.cpp.i

src/Goal.s: src/Goal.cpp.s

.PHONY : src/Goal.s

# target to generate assembly for a file
src/Goal.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Goal.cpp.s
.PHONY : src/Goal.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Moteur2D.o: src/Moteur2D.cpp.o

.PHONY : src/Moteur2D.o

# target to build an object file
src/Moteur2D.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Moteur2D.cpp.o
.PHONY : src/Moteur2D.cpp.o

src/Moteur2D.i: src/Moteur2D.cpp.i

.PHONY : src/Moteur2D.i

# target to preprocess a source file
src/Moteur2D.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Moteur2D.cpp.i
.PHONY : src/Moteur2D.cpp.i

src/Moteur2D.s: src/Moteur2D.cpp.s

.PHONY : src/Moteur2D.s

# target to generate assembly for a file
src/Moteur2D.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Moteur2D.cpp.s
.PHONY : src/Moteur2D.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/Robot.o: src/Robot.cpp.o

.PHONY : src/Robot.o

# target to build an object file
src/Robot.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Robot.cpp.o
.PHONY : src/Robot.cpp.o

src/Robot.i: src/Robot.cpp.i

.PHONY : src/Robot.i

# target to preprocess a source file
src/Robot.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Robot.cpp.i
.PHONY : src/Robot.cpp.i

src/Robot.s: src/Robot.cpp.s

.PHONY : src/Robot.s

# target to generate assembly for a file
src/Robot.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/Robot.cpp.s
.PHONY : src/Robot.cpp.s

src/RobotAtk.o: src/RobotAtk.cpp.o

.PHONY : src/RobotAtk.o

# target to build an object file
src/RobotAtk.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/RobotAtk.cpp.o
.PHONY : src/RobotAtk.cpp.o

src/RobotAtk.i: src/RobotAtk.cpp.i

.PHONY : src/RobotAtk.i

# target to preprocess a source file
src/RobotAtk.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/RobotAtk.cpp.i
.PHONY : src/RobotAtk.cpp.i

src/RobotAtk.s: src/RobotAtk.cpp.s

.PHONY : src/RobotAtk.s

# target to generate assembly for a file
src/RobotAtk.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/RobotAtk.cpp.s
.PHONY : src/RobotAtk.cpp.s

src/RobotDef.o: src/RobotDef.cpp.o

.PHONY : src/RobotDef.o

# target to build an object file
src/RobotDef.cpp.o:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/RobotDef.cpp.o
.PHONY : src/RobotDef.cpp.o

src/RobotDef.i: src/RobotDef.cpp.i

.PHONY : src/RobotDef.i

# target to preprocess a source file
src/RobotDef.cpp.i:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/RobotDef.cpp.i
.PHONY : src/RobotDef.cpp.i

src/RobotDef.s: src/RobotDef.cpp.s

.PHONY : src/RobotDef.s

# target to generate assembly for a file
src/RobotDef.cpp.s:
	$(MAKE) -f CMakeFiles/Roomball.dir/build.make CMakeFiles/Roomball.dir/src/RobotDef.cpp.s
.PHONY : src/RobotDef.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Roomball"
	@echo "... src/Ball.o"
	@echo "... src/Ball.i"
	@echo "... src/Ball.s"
	@echo "... src/Bonus.o"
	@echo "... src/Bonus.i"
	@echo "... src/Bonus.s"
	@echo "... src/BonusSize.o"
	@echo "... src/BonusSize.i"
	@echo "... src/BonusSize.s"
	@echo "... src/Element.o"
	@echo "... src/Element.i"
	@echo "... src/Element.s"
	@echo "... src/Field.o"
	@echo "... src/Field.i"
	@echo "... src/Field.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Goal.o"
	@echo "... src/Goal.i"
	@echo "... src/Goal.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Moteur2D.o"
	@echo "... src/Moteur2D.i"
	@echo "... src/Moteur2D.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/Robot.o"
	@echo "... src/Robot.i"
	@echo "... src/Robot.s"
	@echo "... src/RobotAtk.o"
	@echo "... src/RobotAtk.i"
	@echo "... src/RobotAtk.s"
	@echo "... src/RobotDef.o"
	@echo "... src/RobotDef.i"
	@echo "... src/RobotDef.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

